# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/mec/Scrivania/Exam/lib/graph-tool-2.27/src/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/mec/Scrivania/Exam/lib/graph-tool-2.27/."
package="graph-tool"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "graph-tool-py2.7"
;; --help) pkg-config --help ; echo Buildscript Of "graph-tool Python library"
;; --modversion|--version) echo "2.27"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-L/usr/lib -lpython2.7 -lboost_python"
       :
;; --cflags) echo -I${includedir} "-I/usr/lib/python2.7/dist-packages/graph_tool/include -I/usr/lib/python2.7/dist-packages/graph_tool/include/boost-workaround -I/usr/include/python2.7 -pthread -I/usr/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
